### PR TITLE
Dev/counter update

### PR DESCRIPTION
**Pull request by bighnesh0404**
added functionality to the counters

### CODE REVIEW

**Review by shivamgoyal7 — COMMENTED** [review]
one error: when creates a start new sprint then the document is not creating.

**Comment by shivamgoyal7** [comment]
resolve merge conflict

**Review by shivamgoyal7 — APPROVED** [review]
ready to merge

**Review by shivamgoyal7 — APPROVED** [review]
Ready to merge

**Review by viv9k — APPROVED** [review]

**Pull request merged**
