### PR TITLE
Edit logwork btn

### PR DESCRIPTION
**Pull request by AvinashMahanthi**
### Functionality:
Move Edit and Log work button to submenu bar

### Solution:
added icon to the edit button and moved them to the submenu bar

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
ng serve
go to the task section and open any task
image

### CODE REVIEW

**Review by shivamgoyal7 — CHANGES_REQUESTED** [review]
In mobile view, icons are not properly aligned because the padding on the x-axis is not given properly. Make this correct

**Comment by AvinashMahanthi** [comment]
all changes are done
image

**Review by shivamgoyal7 — APPROVED** [review]
ship it

**Comment by viv9k** [comment]
@shivamgoyal7 How can you give ship it on improperly filled description Pull request, Please follow the guidelines, Or else I will deprecate this pull request.

**Comment by viv9k** [comment]
Log work button also must have an icon

**Comment by AvinashMahanthi** [comment]
image

image

**Review by viv9k — APPROVED** [review]
ship it

**Pull request merged**
