### PR TITLE
Made Heading for Task details

### PR DESCRIPTION
**Pull request by Akshay-Jak**
image

Signed-off-by: Akshay-Jak <akshayjani2147@gmail.com>

### Functionality:
Display heading on top of task card icon

### Solution:
Used Bootstrap to display the headings on top of the task card icons in the task page

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
firebase emulators:start
ng serve

### CODE REVIEW

**Review by shivamgoyal7 — COMMENTED** [review]
add screenshot

**Comment by viv9k** [comment]
Convert the whole thing into ng-bootstrap based table.

**Comment by viv9k** [comment]
I see there are too many changes, that should already be there in the branch, please check for it.

**Comment by Akshay-Jak** [comment]
Closing this pull request because I made same changes in another pull request

**Pull request closed without merging**
