### PR TITLE
feat(userVerification): user verify email API

### PR DESCRIPTION
**Pull request by shivamgoyal7**
### Functionality:
user varification through mail

### Solution:
Mail is sent to all the members to verify user authenticate.

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
firebase deploy

### CODE REVIEW

**Review by shivamgoyal7 — COMMENTED** [review]
I haven't use authguard here because after login it redirect to dashboard.
The code @viv9k u send is work before login.
So i have handle this from UI

**Review by viv9k — APPROVED** [review]
ship it.

**Review by viv9k — CHANGES_REQUESTED** [review]
Please do the required changes

**Review by viv9k — APPROVED** [review]
Ship it

**Pull request merged**
