### PR TITLE
feat(dev/moveData) - created a patch the move data from s-1 to backlog

### PR DESCRIPTION
**Pull request by bighnesh0404**
### Functionality:
move data from s-1 to backlog

### Solution:
created a function called setDataIntoBacklog that moves data from s-1 to backlog

While using this function ,please check the collection name

### CODE REVIEW

**Review by shivamgoyal7 — CHANGES_REQUESTED** [review]
there should be connectivity between index.html and backlogpatch.html.
In backlogpatch.html there should be two input box is present, in which we can write which sprint we have to move and where to move.

**Comment by bighnesh0404** [comment]
> there should be connectivity between index.html and backlogpatch.html.
> In backlogpatch.html there should be two input box is present, in which we can write which sprint we have to move and where to move.

the "s-1" collection will only move to the backlog collection
and this code is a one time use which will be deleted after the use so there doesnt require any connectivity.

**Comment by shivamgoyal7** [comment]
this is not one time.
this patch can be used later for another collection change id required in future.

**Comment by bighnesh0404** [comment]
> this is not one time.
> this patch can be used later for another collection change id required in future.

Since the backlog documents are in s-1, so the documents from the s-1 need to be moved into backlogs and there wont be any future use

**Review by viv9k — APPROVED** [review]
ship it

**Pull request merged**
