### PR TITLE
feat(dev/startNewSprintFix): Fixed some bugs in Create-new-sprint

### PR DESCRIPTION
**Pull request by sid-bagwe**
### Functionality:
Fixed bugs in create new sprint component.

### Solution:
1) The data in now being updated correctly when the team changes 
2) TeamId is displayed on top
3) Blocked the dates before the current date

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start
Check the start new Sprint Page.

### CODE REVIEW

**Review by shivamgoyal7 — APPROVED** [review]
ship it

**Review by arjund-06 — APPROVED** [review]
Ship it

**Comment by viv9k** [comment]
Please resolve merge conflict and check my older comment for this PR

**Review by viv9k — CHANGES_REQUESTED** [review]
Please do the required changes

**Review by viv9k — APPROVED** [review]
Ship it

**Pull request merged**
