### PR TITLE
WorkTrolly Logo

### PR DESCRIPTION
**Pull request by bighnesh0404**
### Functionality:
New Logo for worktrolly

### Solution:
New logo has been implemented

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
ng serve
Screenshot 2021-04-22 222411
Screenshot 2021-04-22 222453

### CODE REVIEW

**Comment by viv9k** [comment]
Please Include images

**Comment by viv9k** [comment]
And fix color for white back ground navbar

**Comment by viv9k** [comment]
Also this is not going to change everything, the favicon will not get fixed with this.

**Comment by viv9k** [comment]
I need demo on this. Please connect with me and show me demo.

**Comment by viv9k** [comment]
I haven't got the demo yet.

**Comment by bighnesh0404** [comment]
> Please Include images

Uploaded

**Review by viv9k — APPROVED** [review]
Ship it

**Pull request merged**
