### PR TITLE
feat(TaskDetail):Fixed details of Task using Snapshot Changes

### PR DESCRIPTION
**Pull request by sandeep-v1404**
### Functionality:
1.Counters ,
2.Update Task Details using SnapshotChanges
### Solution:
1.To make Counters work , bugs are fixed with Promises in logWork , editPageTask , deleteTask Cloud Functions . 
2. Task Details will be Updated asynchronously.
### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
1.ng serve 
2.Try to Edit Task and Delete a Task .
3.Log a Task with Status "Completed" , Then checkout the Task Detail Page . 
4.Task Details will load after Editing or Logging the Task .

### CODE REVIEW

**Review by shivamgoyal7 — CHANGES_REQUESTED** [review]
solve the cors issue in editPage Api

**Review by shivamgoyal7 — APPROVED** [review]
ready to merge

**Review by viv9k — CHANGES_REQUESTED** [review]
The changes from edit task can be removed and updated.

Since it's merged in main code by me. Also check for merge conflict and resolve it.

**Comment by sandeep-v1404** [comment]
Fixing Merge Conflict.. Hence, Closing the PR .

**Pull request closed without merging**
