### PR TITLE
feat(dev/activity): added an activity collection in database.

### PR DESCRIPTION
**Pull request by k0malSharma**
### Functionality:
Adding Activity in collection

### Solution:
Based on the proposed schema, an activity collection is added to the database, to track each activity of the task.

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
1. ng serve
2. create a task and perform operations
3. observe the updated collection on firebase console

An "Activity" collection is created: 
Screenshot (14)

An "Action" collection is created under each taskId:
Screenshot (15)

### CODE REVIEW

**Review by shivamgoyal7 — CHANGES_REQUESTED** [review]
Add username in every activity so that we can know who has performed this activity

**Review by shivamgoyal7 — COMMENTED** [review]
make a separate method to update activity in the database...sou we don't need to write similar code again and again in API's. (i will explain u in the meet)

make service named tool to add date and time.

**Comment by Shrishti1802** [comment]
resolve merge conflict

**Review by shivamgoyal7 — APPROVED** [review]
Ship it

**Pull request merged**
