### PR TITLE
feat(teamThemeFix): Fixed the theme in team-details component

### PR DESCRIPTION
**Pull request by sid-bagwe**
### Functionality:
Earlier the dark theme font color was not applied in the create team and update team, also the UI was not similar to the create new organization page.

### Solution:
Added a style in the team-details component css file to fix it.
Changed the component to create-new-organization component to route to when the user needs to Create or Update Team.

image

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
ng serve
firebase emulators:start
Check the create Team and update Team pages

### CODE REVIEW

**Review by arjund-06 — APPROVED** [review]
Ship it

**Review by viv9k — CHANGES_REQUESTED** [review]
Please fix the UI same as the create new organisation page, if fact better to you the same component as that of create new team in organisation component.

**Comment by k0malSharma** [comment]
Please resolve the merge conflicts

**Review by viv9k — APPROVED** [review]
Ship it

**Comment by viv9k** [comment]
Please resolve the merge conflict

**Comment by sid-bagwe** [comment]
> 
> 
> Please resolve the merge conflict

**Comment by k0malSharma** [comment]
Revert environment.ts and .firebaserc file

**Pull request merged**
