### PR TITLE
feat(status):fixed the status

### PR DESCRIPTION
**Pull request by shreyachowdhury4**
### Functionality:

displaying status

### Solution:

fixed status using 'this' keyword

### Risk level:
- [ ] high 
- [ ] medium
- [X] low

### How to test:
ng serve

### CODE REVIEW

**Review by shivamgoyal7 — APPROVED** [review]
able to merge

**Review by viv9k — APPROVED** [review]
Ship it!

**Comment by viv9k** [comment]
Please resolve merge conflict asap

**Review by viv9k — APPROVED** [review]
Ship it!

**Pull request merged**
